
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: go_app
      POSTGRES_USER: sensei
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8000
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: go_app
      POSTGRES_USER: sensei
      POSTGRES_PASSWORD: 12345
